# Support for implicit masters is deprecated, so we need to explicitly
# specify that this repo depends on Gentoo Portage repo.
masters = gentoo guru
profile-formats = portage-2 profile-set

# Sign Git commits, and NOT Manifests
sign-commits = true
sign-manifests = false
